php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.xdebug
      - server.xdebug
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
